version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sdu_chats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # Внешний порт не публикуем
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sdu_chats"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    # Внешний порт Railway -> внутренний 9090
    ports:
      - "${PORT:-9090}:9090"
    environment:
      # Передаём порт приложению
      SERVER_PORT: "${PORT:-9090}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/sdu_chats"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
