spring:
  application:
    name: SDU Chat bot layer
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sdu_chats
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml

springdoc:
  api-docs.path: /api-docs
  api-docs:
    enabled: ${SWAGGER_SHOW:true}

server:
  port: 9090
  tomcat:
    use-relative-redirects: true

chat:
  azure-openai-url: https://a-ass55.openai.azure.com/
  azure-openai-key: FBx0qou5mQpzUs5cW4itbIk42WlgAj8TpmAjbw5uXPDhp5ckYg2QJQQJ99BIACHYHv6XJ3w3AAABACOGYhoG
  assistant-id: asst_LMHsNblhuLgYt9I2RpMfm3Kr

assistants:
  api-version: "2024-05-01-preview"
  endpoint: "${AZURE_OPENAI_ENDPOINT:https://a-ass55.openai.azure.com/}"
  api-key: "${AZURE_OPENAI_API_KEY:FBx0qou5mQpzUs5cW4itbIk42WlgAj8TpmAjbw5uXPDhp5ckYg2QJQQJ99BIACHYHv6XJ3w3AAABACOGYhoG}"
  assistant-id: "${AZURE_OPENAI_ASSISTANT_ID:asst_LMHsNblhuLgYt9I2RpMfm3Kr}"   # your assistant id
  # poll config
  poll:
    initial-delay-ms: 800
    interval-ms: 1500
    timeout-ms: 60000

  tools:
    websearch:
      provider: serpapi
      serpapi:
        api-key: "${SERPAPI_API_KEY:5b428af6a0a873bbd5d882ce73d5b2aa95e16db84fecebeef032ba7ea7fd47fb}"
        hl: "ru"
        gl: "ru"
        results: 5
    wren:
      url: "${WREN_AI_URL:https://cloud.getwren.ai/api/v1/ask}"
      token: "${WREN_API_TOKEN:sk-Q2nNDxNKzoH77Q}"
      project-id: "${WREN_PROJECT_ID:10875}"
    external:
      url: "${NITEC_EXT_URL:https://nitec-ai.kz/api/chat/completions}"
      token: "${NITEC_AI_BEARER_TOKEN:sk-196c1fe7e5be40b2b7b42bc235c49147}"